# Generated by Django 5.0.6 on 2024-07-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('timbre', models.CharField(max_length=50)),
                ('barrio', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
