# Generated by Django 5.0.6 on 2024-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_direccion_delete_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='timbre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
