# Generated by Django 5.0.6 on 2024-07-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_alter_direccion_nombre_alter_direccion_timbre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='timbre',
            field=models.CharField(default='Sin timbre', max_length=50),
        ),
    ]
