# Generated by Django 5.0.7 on 2024-07-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_alter_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=250)),
                ('anio', models.EmailField(max_length=254)),
                ('genero', models.IntegerField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
