# Generated by Django 5.0.7 on 2024-07-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0009_remove_favorito_portada_libro_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['titulo', 'autor'],
            },
        ),
        migrations.RenameModel(
            old_name='Libro',
            new_name='LibroCatalogo',
        ),
    ]
